# @Time    : 2022/10/20 18:26
# @Author  : Logan.Jin | www.loganjin.cn
# @Project : Zerotier
# @FileName: docker-compose.yml
# @Annotation: 转载请保留来源
version: '3.0'
services:
    ztncui:
        container_name: zerotier-planet
        restart: always
        environment:
            - MYADDR=
            - MYDOMAIN=
            - HTTP_PORT=3000
            - HTTPS_PORT=3443
            - ZTNCUI_PASSWD=loganjin.cn
            - NODE_ENV=production
            - HTTP_ALL_INTERFACES=true
        ports:
            - '3000:3000'
            - '9993:9993'
            - '9993:9993/udp'
            - '3180:3180'
        volumes:
            - './zerotier-one:/var/lib/zerotier-one'
            - './ztncui/etc:/opt/key-networks/ztncui/etc'
        image: loganjindev/zerotier-ztncui
